spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: false

logging:
  level:
    root : info
    org.hibernate.SQL: warn
  #rg.hibernate.type: trace