spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    group:
      "local": "local, common"
      "prod": "prod, common"

